### ISSUE TITLE
podcast feedback about sqlc + one file

### ISSUE THREAD

**Issue by bbkane** [dstpierre/tpl#1]
Hello! I know this isn't the appropriate place to talk about sqlc and your podcast, but I just finished episode 39 on `go podcast()` (which I really enjoyed by the way) and realized you didn't know sqlc can handle your migration approach (ordered files in a migration directory).

This is what I do- see https://github.com/bbkane/envelope/blob/49cba01cb0ed46efbcea126780718e74557c4128/sqlite/sqlc.yaml for an example, and see https://docs.sqlc.dev/en/stable/howto/ddl.html for the docs on it.

Anyway, have a great day, thanks for the podcast.

**Comment by dstpierre** [comment]
Hi @bbkane thanks for the info, this is exactly what I was looking for.
